name = " AbigAIL murugi "
# print(name.casefold())
# print(name.split(" "))
# print(name.swapcase())
# print(name.count("g"))
# print(name.title())
# print(name.encode())
# print(name.expandtabs())
# print(name.isnumeric())
# print(name.isprintable())
# print(name.replace("murugi","injene"))
name = str(name.split().lower())
print(name)
print(type(name))